### ISSUE TITLE
Driver login() function fails due to KeyError

### ISSUE THREAD

**Issue by lucian-cap** [Vaelor/python-mattermost-driver#136]
Following the documentation [here](https://vaelor.github.io/python-mattermost-driver/#authentication) I am attempting to create the driver and call the login function as shown below:

```
from mattermostdriver import Driver

admin = Driver({"login_id": "admin",
                "password": "password123",
                "scheme": "http",
                "url": "localhost:8065/mattermost",})

admin.login()
```

However, I get a KeyError thrown by the login function:
```
Traceback (most recent call last):
  File "mattermost.py", line 9, in <module>
    admin.login()
  File "/home/chase/mattermost/.venv/lib/python3.8/site-packages/mattermostdriver/driver.py", line 179, in login
    self.client.token = response.headers['Token']
  File "/home/chase/mattermost/.venv/lib/python3.8/site-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'token'
```

I've confirmed that going to http://localhost:8065/mattermost successfully prompts me for login info & the info above successfully logs in. I used this module several months ago without issue so I'm not sure what's going wrong now with how I'm using it.

**Comment by lucian-cap** [comment]
Apologies, I wasn't passing the right options in.
