### ISSUE TITLE
Upload_file doesn`t work for image files?

### ISSUE THREAD

**Issue by elpatron68** [Vaelor/python-mattermost-driver#3]
This may be an API issue, but perhaps someone can help me:

I don' have no problem to upload quite any file type, but image files (jpg, png) are rejected:

```
Traceback (most recent call last):
  File "d:\Users\Markus\Documents\python\imagequote\mmtest.py", line 60, in <module>
    files={'files': (FILENAME, open(FILENAME))}
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\mattermostdriver\endpoints\files.py", line 11, in upload_file
    files=files
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\mattermostdriver\client.py", line 135, in post
    return self.make_request('post', endpoint, options=options, params=params, data=data, files=files).json()
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\mattermostdriver\client.py", line 109, in make_request
    files=files
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\requests\api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\requests\models.py", line 308, in prepare
    self.prepare_body(data, files, json)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\requests\models.py", line 496, in prepare_body
    (body, content_type) = self._encode_files(files, data)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\requests\models.py", line 159, in _encode_files
    fdata = fp.read()
  File "C:\Program Files (x86)\Python36-32\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 172: character maps to <undefined>
```

I have no idea how to investigate the problem. Mattermost's API documentation doesn' t help either.

Thanks for help & for this project!

Markus

**Comment by Vaelor** [comment]
Hi, maybe changing
`    files={'files': (FILENAME, open(FILENAME))}` to `    files={'files': (FILENAME, open(FILENAME, 'rb'))}`
for reading the file in binary mode, helps.
If I recall correctly, the default is only 'r' if no mode is passed, which means 'read as text'.

**Comment by elpatron68** [comment]
Thanks a lot, haven't thought of this option, now it works!
