### ISSUE TITLE
Unable to create customer emojis

### ISSUE THREAD

**Issue by maxbrunet** [Vaelor/python-mattermost-driver#32]
It is probably a silly tasks but I try to upload emojis and I miserably fail. 😁

Here's my non-working code:

```python
emoji_name = "test"
image_path = "test.gif"

with open(image_path, "rb") as image:
    files = {"image": image}
    mm.emoji.create_custom_emoji(emoji_name=emoji_name, files=files)
```

which gives me:

```python
Invalid or missing emoji in request body
Traceback (most recent call last):
  File "/Users/max/.pyenv/versions/mmemoji/lib/python3.7/site-packages/mattermostdriver/client.py", line 140, in make_request
    response.raise_for_status()
  File "/Users/max/.pyenv/versions/mmemoji/lib/python3.7/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://mattermost.example.org:443/api/v4/emoji

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mmemoji_other.py", line 20, in <module>
    mm.emoji.create_custom_emoji(emoji_name=emoji_name, files=files)
  File "/Users/max/.pyenv/versions/mmemoji/lib/python3.7/site-packages/mattermostdriver/endpoints/emoji.py", line 11, in create_custom_emoji
    files=files
  File "/Users/max/.pyenv/versions/mmemoji/lib/python3.7/site-packages/mattermostdriver/client.py", line 174, in post
    return self.make_request('post', endpoint, options=options, params=params, data=data, files=files).json()
  File "/Users/max/.pyenv/versions/mmemoji/lib/python3.7/site-packages/mattermostdriver/client.py", line 145, in make_request
    raise InvalidOrMissingParameters(data['message'])
mattermostdriver.exceptions.InvalidOrMissingParameters: Invalid or missing emoji in request body
```

According to the [Mattermost API Reference](https://api.mattermost.com/#tag/emoji%2Fpaths%2F~1emoji%2Fpost), this endpoint needs:

> **FormData Parameters**
> * `image` file **Required**
>   A file to be uploaded
> * `emoji` string **Required**
>   A JSON object containing a `name` field with the name of the emoji and a `creator_id` field with the id of the authenticated user.

The driver only provide a `name` for the `emoji` object:
https://github.com/Vaelor/python-mattermost-driver/blob/3c5068187cf790ad83a063d36f60032b0164c34c/src/mattermostdriver/endpoints/emoji.py#L10

I also checked a few other drivers, use cases of them and the server side code which seem to confirm the need of a `creator_id` (I can give details if it helps).

So I tried to work around it but I get the exact same error:

```python
creator_id = mm.users.get_user(user_id="me")["id"]
with open(image_path, "rb") as image:
    data = {"emoji": {"name": emoji_name, "creator_id": creator_id}}
    files = {"image": image}
    mm.client.post("/emoji", data=data, files=files)
```

What else do I miss?

The creation of the emoji with same file and name via the Web UI perfectly works.

**Comment by maxbrunet** [comment]
I have found the solution:
> `emoji` A JSON object...

```python
with open(image_path, "rb") as image:
     files = {"image": image}
     emoji = {"name": emoji_name, "creator_id": creator_id}
     data = {"emoji": json.dumps(emoji)}
     mm.client.post("/emoji", data=data, files=files)
```

I'm going open a PR to fix this.
