### ISSUE TITLE
Support bot tokens

### ISSUE THREAD

**Issue by dmpe** [Vaelor/python-mattermost-driver#66]
HI @Vaelor, 
Are bot tokens supported ?

https://docs.mattermost.com/developer/bot-accounts.html

Because I cannot get it work it seems.
Created a bot account in MT and then

```
import os, sys
import urllib3
import requests
urllib3.disable_warnings()
from mattermostdriver import Driver

mt = Driver(
    {
        "url": "on prem MT",
        "token": "s1z1g6sqp...........w",
        "verify": False,
        "port": 443,
        "debug": True,
    }
)
mt.login()
# print(mt.users.get_user(user_id="me"))

mt.posts.create_post(
    options={
        "channel_id": "j9d13993o............mo",
        "message": "This is the important file",
    }
)
```

Then:

```
keep-alive\r\nAuthorization: Bearer s1xxxxxx7ahhmrw\r\nContent-Length: 2\r\nContent-Type: application/json\r\n\r\n'
send: b'{}'
reply: 'HTTP/1.1 401 Unauthorized\r\n'
header: Content-Length: 186
header: Content-Type: application/json
header: Date: Wed, 06 May 2020 12:34:05 GMT
header: Expires: 0
header: Set-Cookie: MMAUTHTOKEN=; Path=/; Max-Age=0; HttpOnly
header: Vary: Accept-Encoding
header: X-Request-Id: hw63wjjj7jyebf3m4zhrtsnssw
header: X-Version-Id: 5.22.0.5.22.1.
Invalid or expired session, please login again.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/mattermostdriver/client.py", line 162, in make_request
    response.raise_for_status()
  File "/home/xxxxxxxxxxxx/.local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://URL:443/api/v4/users/me

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../update/mt.py", line 19, in <module>
    mt.login()
  File "/usr/local/lib/python3.6/site-packages/mattermostdriver/driver.py", line 162, in login
    result = self.users.get_user('me')
  File "/usr/local/lib/python3.6/site-packages/mattermostdriver/endpoints/users.py", line 45, in get_user
    self.endpoint + '/' + user_id
  File "/usr/local/lib/python3.6/site-packages/mattermostdriver/client.py", line 193, in get
    response = self.make_request('get', endpoint, options=options, params=params)
  File "/usr/local/lib/python3.6/site-packages/mattermostdriver/client.py", line 175, in make_request
    raise NoAccessTokenProvided(message)
mattermostdriver.exceptions.NoAccessTokenProvided: Invalid or expired session, please login again.
```

Any tips ?

**Comment by dmpe** [comment]
My mistake -> it is not token ID but token access code. 
sorry. it works just about very well!
