### ISSUE TITLE
exception translation results in confusing backtraces

### ISSUE THREAD

**Issue by jetpackdanger** [Vaelor/python-mattermost-driver#69]
For example, with bogus terms in `search_criteria`:

```
>>> mm.users.search_users(search_criteria)
Invalid or missing term in request body.
Traceback (most recent call last):
  File "/home/paul/.local/lib/python3.8/site-packages/mattermostdriver/client.py", line 162, in make_request
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://chat.example.com:443/api/v4/users/search

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/paul/.local/lib/python3.8/site-packages/mattermostdriver/endpoints/users.py", line 32, in search_users
    return self.client.post(
  File "/home/paul/.local/lib/python3.8/site-packages/mattermostdriver/client.py", line 206, in post
    return self.make_request('post', endpoint, options=options, params=params, data=data, files=files).json()
  File "/home/paul/.local/lib/python3.8/site-packages/mattermostdriver/client.py", line 173, in make_request
    raise InvalidOrMissingParameters(message)
mattermostdriver.exceptions.InvalidOrMissingParameters: Invalid or missing term in request body.
>>> _
```

This makes the traceback more difficult to read than necessary.  I did a little research and it seems that translating exceptions as follows:

```
raise MyFriendlyException() from None
```

should suppress the original exception and yield a clean traceback.

**Comment by jetpackdanger** [comment]
For example, this:
```diff
--- /home/paul/.local/lib/python3.8/site-packages/mattermostdriver/client.py.orig       2020-07-02 15:27:32.978908905 +1200
+++ /home/paul/.local/lib/python3.8/site-packages/mattermostdriver/client.py    2020-07-02 15:25:41.202608897 +1200
@@ -170,19 +170,19 @@
                        log.error(message)
                        # pylint: disable=no-else-raise
                        if e.response.status_code == 400:
-                               raise InvalidOrMissingParameters(message)
+                               raise InvalidOrMissingParameters(message) from None
                        elif e.response.status_code == 401:
-                               raise NoAccessTokenProvided(message)
+                               raise NoAccessTokenProvided(message) from None
                        elif e.response.status_code == 403:
-                               raise NotEnoughPermissions(message)
+                               raise NotEnoughPermissions(message) from None
                        elif e.response.status_code == 404:
-                               raise ResourceNotFound(message)
+                               raise ResourceNotFound(message) from None
                        elif e.response.status_code == 405:
-                               raise MethodNotAllowed(message)
+                               raise MethodNotAllowed(message) from None
                        elif e.response.status_code == 413:
-                               raise ContentTooLarge(message)
+                               raise ContentTooLarge(message) from None
                        elif e.response.status_code == 501:
-                               raise FeatureDisabled(message)
+                               raise FeatureDisabled(message) from None
                        else:
                                raise

```

yielded

```
>>> mm.users.get_user(user_id='pjdc')
Invalid or missing user_id parameter in request URL.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/paul/.local/lib/python3.8/site-packages/mattermostdriver/endpoints/users.py", line 44, in get_user
    return self.client.get(
  File "/home/paul/.local/lib/python3.8/site-packages/mattermostdriver/client.py", line 193, in get
    response = self.make_request('get', endpoint, options=options, params=params)
  File "/home/paul/.local/lib/python3.8/site-packages/mattermostdriver/client.py", line 173, in make_request
    raise InvalidOrMissingParameters(message) from None
mattermostdriver.exceptions.InvalidOrMissingParameters: Invalid or missing user_id parameter in request URL.
>>> _
```

**Comment by Vaelor** [comment]
@jetpackdanger Hey! That sounds like a really good idea, if you want you can submit a PR for that, since you actually already did that? If not, I would just copy/paste your code sometime this week.
