### ISSUE TITLE
Getting invalid URL error

### ISSUE THREAD

**Issue by sparsh-1000** [Vaelor/python-mattermost-driver#90]
Hi, 
I am getting the following error while launching errbot with backend set to a mattermost instance. 

```
15:20:12 ERROR    errbot.backends.base      Exception occurred in serve_once:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/errbot/backends/base.py", line 861, in serve_forever
    if self.serve_once():
  File "/root/errbot-root/errbot-mattermost-backend/mattermost.py", line 311, in serve_once
    self.driver.login()
  File "/usr/local/lib/python3.6/site-packages/mattermostdriver/driver.py", line 171, in login
    result = self.users.get_user('me')
  File "/usr/local/lib/python3.6/site-packages/mattermostdriver/endpoints/users.py", line 45, in get_user
    self.endpoint + '/' + user_id
  File "/usr/local/lib/python3.6/site-packages/mattermostdriver/client.py", line 193, in get
    response = self.make_request('get', endpoint, options=options, params=params)
  File "/usr/local/lib/python3.6/site-packages/mattermostdriver/client.py", line 162, in make_request
    response.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 411 Client Error: Length Required for url: http://SERVER_IP_HERE:8065/mm:8065/api/v4/users/me
15:20:12 INFO     errbot.backends.base      Reconnecting in 1 seconds (0 attempted reconnections so far).
15:20:13 DEBUG    urllib3.connectionpool    Starting new HTTP connection (1): PROXY_IP_HERE
15:20:13 DEBUG    urllib3.connectionpool    http://PROXY_IP_HERE "GET http://SERVER_IP_HERE:8065/mm:8065/api/v4/users/me HTTP/1.1" 411 4390
15:20:13 ERROR    mattermostdriver.websocke <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>ERROR: The requested URL could not be retrieved</title>
```

This is followed by html data of a webpage with the message "The requested URL could not be retrieved" 

***

I have configured Mattermost such that the URL (http://SERVER_IP_HERE:8065/mm:8065/api/v4/users/me) automatically redirects on Mattermost login page (tested the same on another server). 

There should not be any access related issue as Mattermost and Errbot are installed on the same server (represented here with SERVER_IP_HERE).

Let me know if any additional information is required.
Please Help!

**Comment by Vaelor** [comment]
Hey @sparsh-1000

Can you check the url you use? It looks really strange to me, that you have like...
`http://1.2.3.4:8065/mm:8065/...` in there. Is that really correct? I would assume it should be either `http://1.2.3.4:8065/...` or `http://mm:8065/...`

I saw that you mentioned, you configured mattermost to work like that, but it does look a bit strange.
Also, the backend for mattermost for errbot may be a bit out of date. It uses an older version of this repository here and I haven't been actively updating it for a while.

Could you try to reproduce the error without errbot, only using this library?
Another possibility could be the proxy, maybe it is incorrectly configured (the 411 Client Error: Length required is a bit strange).

Sorry for being so vague but that error is kinda hard for me to understand since you seem to have a kinda unique environment set up I do not understand so far.

**Comment by sparsh-1000** [comment]
Update:

I added an exception in my proxy settings, so that it would let local URLs pass through. I am getting a different error now when I run errbot:

```
19:34:33 INFO     errbot.bootstrap          Found Storage plugin: Shelf.
19:34:33 INFO     errbot.bootstrap          Found Backend plugin: Mattermost
19:34:33 DEBUG    errbot.storage            Opening storage 'repomgr'
19:34:33 DEBUG    errbot.storage.shelf      Open shelf storage /root/errbot-root/data/repomgr.db
19:34:33 DEBUG    errbot.core               ErrBot init.
19:34:33 DEBUG    errbot.backends.base      Backend init.
19:34:33 DEBUG    errbot.core               created a thread pool of size 10.
19:34:33 DEBUG    errbot.storage            Opening storage 'core'
19:34:33 DEBUG    errbot.storage.shelf      Open shelf storage /root/errbot-root/data/core.db
19:34:33 DEBUG    errbot.core               Initializing backend storage
19:34:33 DEBUG    errbot.storage            Opening storage 'mattermost_backend'
19:34:33 DEBUG    errbot.storage.shelf      Open shelf storage /root/errbot-root/data/mattermost_backend.db
19:34:33 DEBUG    errbot.plugin_manager     New entries added to sys.path:
19:34:33 DEBUG    errbot.plugin_manager     /usr/local/lib/python3.6/site-packages/errbot/core_plugins
19:34:33 DEBUG    errbot.plugin_manager     /root/errbot-root/plugins/err-example
19:34:33 DEBUG    errbot.plugins.Utils      Logger for plugin initialized...
19:34:33 DEBUG    errbot.plugins.CommandNot Logger for plugin initialized...
19:34:33 DEBUG    errbot.plugins.Backup     Logger for plugin initialized...
19:34:33 DEBUG    errbot.plugins.TextCmds   Logger for plugin initialized...
19:34:33 DEBUG    errbot.plugins.ACLs       Logger for plugin initialized...
19:34:33 DEBUG    errbot.plugins.Help       Logger for plugin initialized...
19:34:33 DEBUG    errbot.plugins.Plugins    Logger for plugin initialized...
19:34:33 DEBUG    errbot.plugins.ChatRoom   Logger for plugin initialized...
19:34:33 DEBUG    errbot.plugins.VersionChe Logger for plugin initialized...
19:34:33 DEBUG    errbot.plugins.Flows      Logger for plugin initialized...
19:34:33 INFO     errbot                    webhooks:  Flag to bind /echo to echo
19:34:33 DEBUG    errbot.plugins.Webserver  Logger for plugin initialized...
19:34:33 DEBUG    errbot.plugins.Health     Logger for plugin initialized...
19:34:33 DEBUG    errbot.plugins.Example    Logger for plugin initialized...
19:34:33 DEBUG    errbot.bootstrap          Start serving commands from the mattermost backend.
19:34:33 DEBUG    urllib3.connectionpool    Starting new HTTP connection (1): SERVER_IP_HERE:8065
19:34:33 DEBUG    urllib3.connectionpool    http://SERVER_IP_HERE:8065 "GET /mm:8065/api/v4/users/me HTTP/1.1" 200 3677
19:34:33 DEBUG    urllib3.connectionpool    Starting new HTTP connection (1): SERVER_IP_HERE:8065
19:34:33 DEBUG    urllib3.connectionpool    http://SERVER_IP_HERE:8065 "GET /mm:8065/api/v4/teams/name/TEAM_NAME HTTP/1.1" 200 3677
19:34:33 ERROR    errbot.backends.base      Exception occurred in serve_once:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/errbot/backends/base.py", line 861, in serve_forever
    if self.serve_once():
  File "/root/errbot-root/errbot-mattermost-backend/mattermost.py", line 313, in serve_once
    self.teamid = self.driver.teams.get_team_by_name(name=self.team)['id']
TypeError: 'Response' object is not subscriptable
```

**Comment by sparsh-1000** [comment]
Hi @Vaelor 

Issue solved. I changed the URL to a simpler one (`http://1.2.3.4:8065/`). Its working now. Thanks a lot!
